### ISSUE TITLE
CRUD

### ISSUE THREAD

**Issue by revan7997** [smhlana/dotnet-api-cosmosdb#1]
you can do delete, read, update operation for this code

**Comment by smhlana** [comment]
@revan7997 I'm not sure if that is a question. If it is, the answer is no, you can not do delete and update. If you look at the controller code you'll see there are only 2 endpoints to create and read.

**Comment by revan7997** [comment]
sorry for wrong question, I wanted to know how add Delete Operation code and update operation code in your program.

**Comment by smhlana** [comment]
@revan7997 

    // Add the following to delete an item:
    public async Task DeleteItemAsync(string id)
    {
        await this._container.DeleteItemAsync<Item>(id, new PartitionKey(item.Country));
    }
    
    // Add the following to update an item:
    public async Task UpdateItemAsync(Item item)
    {
        await this._container.UpsertItemAsync<Item>(item, new PartitionKey(item.Country));
    }

    // You'll then have to add endpoints for these operations. Something like:
    [HttpDelete("{id}")]     // Delete: api/cities/{id}
    [ActionName("Delete")]
    public async Task<ActionResult> Delete()	   
    {
        await _cosmosDbService.DeleteItemAsync(id);
        return RedirectToAction("Index");   
    }

    [HttpPut("update")]    // Put: api/cities/update
    [ActionName("Update")]
    public async Task<ActionResult> UpdateAsync([Bind("Id,Name,Country,ZipCode")] Item item)
    {
        if (ModelState.IsValid)
        {
            await _cosmosDbService.UpdateItemAsync(item);
            return RedirectToAction("Index");  
        }
        return StatusCode(500);
    }
